# 服务端口
server:
  port: 8090
spring:
  # ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:3b
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: aaa
      chat:
        options:
          model: qwen-max-latest
    zhipuai:
      api-key: aaa
      chat:
        options:
          model: glm-4.7-flash
          temperature: 0.7
  # redis 配置
  data:
    redis:
      host: 127.0.0.1 # 设置redis地址
      port: 6379 # 设置redis端口
      database: 0 # 设置redis数据库索引
      timeout: 10000 # 连接超时时间
      lettuce:
        pool:
          max-wait: -1 # 最大等待时间（-1 没有限制）
          max-idle: 5 # 最大空闲连接数
          min-idle: 0 # 最小空闲连接数
          max-active: 20 # 最大连接数

  # mysql 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fen_dou_chats?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: aaa

  devtools:
    restart:
      enabled: false # 禁用热部署

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# netty 配置
netty:
  host: 127.0.0.1
  port: 9090

# 文件存储配置
storage:
  # 存储策略支持 local 默认：local
  strategy: local
  local:
    domain: http://127.0.0.1:${server.port} # 域名
    path: D://chat # 文件存储路径,本地存储

# 日志配置
logging:
  level:
    com.chat: debug
    org.springframework: info


